### ISSUE TITLE
stat /etc/resolv.conf: no such file or directory

### ISSUE THREAD

**Issue by jannson** [jnwhiteh/golang#4]
I build a soft written by go, and I get "stat /etc/resolv.conf: no such file or directory".  Because my linux version has no "/etc/resolv.conf" file and the root filesystem is readonly.

The more detail is hear:
https://github.com/inconshreveable/ngrok/issues/151

**Comment by jnwhiteh** [comment]
This is a mirror, please join the primary repository.

https://github.com/golang/go
