### ISSUE TITLE
go tool dist: FAILED: hg identify -b

### ISSUE THREAD

**Issue by cogbee** [jnwhiteh/golang#5]
when I try to install golang,I meet a problem:

root@ubuntu:~/Desktop/golang-master/src$ ./all.bash 
   # Building C bootstrap tool.
cmd/dist
go tool dist: FAILED: hg identify -b
./make.bash: eval: line 135: syntax error near unexpected token `('
root@ubuntu:~/Desktop/golang-master/src$ 

my sourcecode comes from github. 
could you give me a hand.

**Comment by jnwhiteh** [comment]
This is a mirror, please join the primary repository.

https://github.com/golang/go
