### ISSUE TITLE
build failed on linux/arm

### ISSUE THREAD

**Issue by 0312birdzhang** [jnwhiteh/golang#6]
I use ./all.bash and ./make.bash build
after finished, only a "gofmt" in go/bin 

logs:
http://pastebin.com/sfW7zBXQ#
ps:because wrong markdown format,i paste the code to pastebin

**Comment by jnwhiteh** [comment]
This is an old mirror, please consult the real repository.

https://github.com/golang/go

**Comment by 0312birdzhang** [comment]
thanks :)
